const BD_UNIS = require("./index");

let uni = new BD_UNIS();

test("Check PhD ", () => {
  expect(uni.havePHD("University of Dhaka")).toBe(true);
});

test("get All Names and ", () => {
  expect(uni.havePHD("University of Dhaka")).toBe(true);
  expect(uni.getNames()).toEqual([
    "University of Dhaka",
    "University of Rajshahi",
    "Bangladesh Agricultural University",
    "Bangladesh University of Engineering & Technology",
    "University of Chittagong",
    "Jahangirnagar University",
    "Islamic University, Bangladesh",
    "Shahjalal University of Science and Technology",
    "Khulna University",
    "Bangabandhu Sheikh Mujib Medical University ",
    "Bangabandhu Sheikh Mujibur Rahman Agricultural University",
    "Hajee Mohammad Danesh Science & Technology University",
    "Mawlana Bhashani Science and Technology University",
    "Patuakhali Science and Technology University",
    "Sher-e-Bangla Agricultural University",
    "Dhaka University of Engineering & Technology",
    "Rajshahi University of Engineering & Technology",
    "Chittagong University of Engineering & Technology",
    "Khulna University of Engineering & Technology",
    "Jagannath University",
    "Jatiya Kabi Kazi Nazrul Islam University",
    "Chittagong Veterinary and Animal Sciences University",
    "Sylhet Agricultural University",
    "Comilla University",
    "Noakhali Science and Technology University",
    "Jessore University of Science & Technology",
    "Pabna University of Science and Technology",
    "Bangladesh University of Professionals",
    "Begum Rokeya University",
    "Bangladesh University of Textiles",
    "University of Barisal",
    "Bangabandhu Sheikh Mujibur Rahman Science and Technology University",
    "Bangabandhu Sheikh Mujibur Rahman Maritime University",
    "Rangamati Science and Technology University",
    "Rabindra University",
    "Bangabandhu Sheikh Mujibur Rahman Digital University",
    "Sheikh Hasina University",
    "Bangamata Sheikh Fojilatunnesa Mujib Science & Technology University",
    "University",
    "Gono Bishwabidyalay",
    "Ahsanullah University of Science and Technology",
    "BRAC University",
    "East West University",
    "North South University",
    "American International University-Bangladesh",
    "Independent University, Bangladesh",
    "Bangladesh University of Business and Technology",
    "Dhaka International University",
    "Hamdard University Bangladesh",
    "International Islamic University, Chittagong",
    "BGC Trust University Bangladesh",
    "Chittagong Independent University (CIU)",
    "University of Science & Technology Chittagong",
    "East Delta University",
    "Bangladesh Army University of Science and Technology",
    "Bangladesh Army International University of Science & Technology",
    "Britannia University",
    "CCN University of Science & Technology",
    "Feni University",
    "Bangladesh Army University of Engineering & Technology",
    "Premier University, Chittagong",
    "Exim Bank Agricultural University Bangladesh",
    "Southern University, Bangladesh",
    "Port City International University",
    "Coxs Bazar International University",
    "Notre Dame University Bangladesh",
    "Asian University of Bangladesh",
    "Asa University Bangladesh",
    "Atish Dipankar University of Science and Technology",
    "Bangladesh Islami University",
    "Bangladesh University",
    "Central Women's University",
    "City University, Bangladesh",
    "Daffodil International University",
    "Eastern University, Bangladesh",
    "Green University of Bangladesh",
    "IBAIS University",
    "Sonargaon University",
    "International University of Business Agriculture and Technology",
    "Manarat International University",
    "Millennium University",
    "Northern University, Bangladesh",
    "North Western University, Bangladesh",
    "The University of Comilla, Bangladesh",
    "People's University of Bangladesh",
    "Presidency University",
    "Pundra University of Science and Technology",
    "Prime University",
    "European University of Bangladesh",
    "Primeasia University",
    "Queens University",
    "Rajshahi Science & Technology University",
    "Royal University of Dhaka",
    "Shanto-Mariam University of Creative Technology",
    "Southeast University",
    "Stamford University Bangladesh",
    "State University of Bangladesh",
    "United International University",
    "University of Asia Pacific (Bangladesh)",
    "University of Development Alternative",
    "University of Information Technology and Sciences",
    "University of Liberal Arts Bangladesh",
    "Fareast International University",
    "University of South Asia, Bangladesh",
    "Uttara University",
    "Victoria University of Bangladesh",
    "Varendra University",
    "World University of Bangladesh",
    "Leading University",
    "Metropolitan University",
    "North East University Bangladesh",
    "Sylhet International University",
    "Khwaja Yunus Ali University",
    "Global University Bangladesh",
    "University of Creative Technology Chittagong",
    "Z H Sikder University of Science & Technology",
    "Central University of Science and Technology",
    "Canadian University of Bangladesh",
    "First Capital University of Bangladesh",
    "Ishaka International University",
    "Northern University of Business & Technology, Khulna",
    "North Bengal International University",
    "Ranada Prasad Shaha University",
    "Bangladesh University of Health Sciences",
    "BGMEA University of Fashion & Technology",
    "Islamic University of Technology",
    "Asian University for Women",
    "Bangladesh Open University",
    "National University of Bangladesh",
    "Islamic Arabic University"
  ]);
});
